### ISSUE TITLE
Please add LICENSE file

### ISSUE THREAD

**Issue by javierpena** [bninja/pika-pool#7]
I'm trying to package pika-pool for Fedora, and the Fedora licensing guidelines (https://fedoraproject.org/wiki/Packaging:LicensingGuidelines#License_Text) require that the license text is included in the package.

From https://github.com/bninja/pika-pool/blob/master/setup.py#L14 , I understand pika-pool is licensed under the BSD license, would it be possible to add it to the repository? http://directory.fsf.org/wiki/License:BSD_3Clause can be a good source to take it from, if needed.

Thanks!

**Comment by albertomurillo** [comment]
Hi. I want to package pika-pool for ClearLinux and I ran into the same issue.
Please add a license file.

**Comment by laca-** [comment]
Me too.  I imagine this is a problem for most distributions.
Please add a license file.

**Comment by bninja** [comment]
@javierpena sorry for delay. i dont monitor this stuff anymore.
